USE [empresa]
GO

IF OBJECT_ID(N'dbo.PARTIDO', N'U') IS  NOT NULL
	BEGIN
		DROP TABLE [dbo].[PARTIDO]
	END 




IF OBJECT_ID(N'dbo.PARTIDO', N'U') IS   NULL
BEGIN
	SET ANSI_NULLS ON


	SET QUOTED_IDENTIFIER ON

	CREATE TABLE [dbo].[PARTIDO](
		[id] [int] IDENTITY(1,1) NOT NULL,
		[nombre] [varchar](50) NOT NULL,
		[porcentaje] [real] NOT NULL,
		[numero_votos] [int] NOT NULL,
		CONSTRAINT UC_PARTIDO_NOMBRE UNIQUE (nombre),
	 CONSTRAINT [PK_PARTIDO] PRIMARY KEY CLUSTERED 
	(
		[id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]

	

END


